add_newline = false
scan_timeout = 100
format = "$custom$directory$git_branch$git_status$character"

[custom.machine]
command = "$HOME/.local/bin/prompt-host"
when = "true"
format = "[$output]($style) "
style = "245"

[directory]
format = "[in](245) [$path]($style) "
style = "bold cyan"
truncation_length = 3
truncation_symbol = "../"
truncate_to_repo = false

[git_branch]
format = "[$branch]($style) "
style = "242"
symbol = ""

[git_status]
format = "[$all_status]($style)"
style = "242"
modified = "•"
untracked = "?"
staged = "+"
conflicted = "!"
ahead = ""
behind = ""
diverged = ""
up_to_date = ""
renamed = ""
deleted = ""
stashed = ""

[character]
success_symbol = "[\\$](245) "
error_symbol = "[\\$](red) "
vimcmd_symbol = "[\\$](green) "
vimcmd_replace_one_symbol = "[\\$](red) "
vimcmd_replace_symbol = "[\\$](red) "
vimcmd_visual_symbol = "[\\$](yellow) "
